# Generated by Django 3.2.18 on 2023-03-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0006_auto_20230313_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
